name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate resources and build with Gradle
        run: |
          ./gradlew runData --stacktrace
          ./gradlew clean build --stacktrace

      - name: Upload generated resources
        uses: actions/upload-artifact@v4
        with:
          name: generated-resources
          path: src/generated/resources/assets/exoequipment/
          if-no-files-found: error
